Repository BoltApp/bolt-magento2, pull requests merged in 2018-12, with the labels that each got.

#162 prevent order ceation API call with an empty cart
  view/frontend/templates/js/replacejs.phtml
Labels: bugfix

#163 webhook fixes: invalid capture amount, payment review status
  Helper/Order.php
Labels: bugfix

#168 Update: send GiftCard amount.
  Model/Api/DiscountCodeValidation.php
Labels: bugfix

#172 (Admin) Fixed an order creation issue (2.1.0-2.1.3)
  Observer/Adminhtml/Sales/OrderCreateProcessDataObserver.php
  etc/adminhtml/events.xml
Labels: bug, enhancement

#175 Unirgy_GiftCert module: Fixed throwing exception.
  Model/Api/DiscountCodeValidation.php
Labels: bug

#173 Amasty gift card
  Helper/Cart.php
  Helper/Config.php
  Helper/Discount.php
  Helper/Order.php
  Model/Api/DiscountCodeValidation.php
  Model/ThirdPartyModuleFactory.php
  Plugin/AmastyGiftCardRemovePlugin.php
  etc/di.xml
  etc/frontend/di.xml
  view/frontend/templates/js/replacejs.phtml
Labels: enhancement
