Repository BoltApp/bolt-magento2, pull requests merged in 2019-03, with the labels that each got.

#228 prevent setting empty hint
  view/frontend/templates/js/replacejs.phtml
Labels: bugfix

#230 Back office order creation fix
  Helper/Cart.php
  view/adminhtml/templates/boltpay/js/replacejs.phtml
Labels: bugfix, enhancement

#239 Allow Admin to update order manually
  Helper/Order.php
Labels: bug

#240 back-office create order check for shipping method
  Helper/Cart.php
Labels: bugfix
