Repository BoltApp/bolt-magento2, pull requests merged in 2019-02, with the labels that each got.

#206 Unirgy_Giftcert plugin support
  Helper/Cart.php
  Helper/Discount.php
  etc/di.xml
Labels: enhancement

#211 Reserve Order ID for the child quote, copy it to parent just before the quote to order submit
  Helper/Cart.php
  Helper/Discount.php
  Helper/Order.php
  Setup/UpgradeSchema.php
Labels: bugfix, enhancement

#214 remove active quote restriction on order creation
  Helper/Cart.php
  Helper/Order.php
Labels: bugfix
