Repository BoltApp/bolt-magento2, pull requests merged in 2019-04, with the labels that each got.

#247 back-office order creation shipping selected check update
  view/adminhtml/templates/boltpay/js/replacejs.phtml
Labels: bugfix

#252 Add discount back to shipping amount when address doesn't allow discount
  Api/Data/ShippingOptionsInterface.php
  Helper/Config.php
  Model/Api/Data/ShippingOptions.php
  Model/Api/DiscountCodeValidation.php
  Model/Api/ShippingMethods.php
  Test/Unit/Model/Api/ShippingMethodsTest.php
Labels: enhancement

#253 Include the street address in shipping and tax cache identifier
  Controller/Shipping/Prefetch.php
  Model/Api/ShippingMethods.php
Labels: bugfix

#257 skip quote replication if source and destination are the same
  Helper/Cart.php
Labels: bugfix, enhancement

#260 conditionally override page-cache.js only for store versions prior to 2.2.0
  Plugin/RequireJs.php
  etc/di.xml
Labels: bugfix, enhancement

#258 Partial void implementation
  Helper/Order.php
  Model/Api/OrderManagement.php
Labels: enhancement

#264 eliminate Magento_Customer/js/section-config error
  view/frontend/templates/js/replacejs.phtml
Labels: bugfix
