Repository BoltApp/bolt-magento2, pull requests merged in 2019-07, with the labels that each got.

#318 Aheadworks store credit
  Helper/Cart.php
  Helper/Discount.php
  etc/di.xml
Labels: enhancement

#321 removed redundant area code emulation
  Helper/Order.php
Labels: bug

#319 amasty reward points support
  Helper/Cart.php
  Helper/Discount.php
  Helper/Order.php
  Model/Api/ShippingMethods.php
  Test/Unit/Helper/CartTest.php
  Test/Unit/Model/Api/ShippingMethodsTest.php
  etc/di.xml
Labels: enhancement

#320 Collect immutable quote totals when checking if the coupon is invalid for the shipping address
  Model/Api/ShippingMethods.php
Labels: bug

#322 Fix for accepting pending discount codes
  Model/Api/DiscountCodeValidation.php
Labels: bugfix

#323 Fix for the failed payment validation logic
  Helper/Order.php
  Model/Api/CreateOrder.php
Labels: bugfix

#324 merchant scoped account hints data format fix
  Helper/Cart.php
Labels: bugfix

#325 Add apple pay prefill hints fix
  Helper/Cart.php
Labels: bugfix

#326 Do not allow checkout after Declined Payment card
  Model/Api/CreateOrder.php
Labels: bugfix, enhancement

#331 Remove redundant BoltCheckout.configure
  view/frontend/templates/js/boltjs.phtml
Labels: enhancement

#332 Back office button load fix
  Controller/Adminhtml/Cart/Data.php
  Helper/Cart.php
Labels: bugfix, enhancement

#333 Aheadworks store credit back office fix
  Helper/Cart.php
Labels: bugfix

#336 Async attribute added to the bolt-connect script
  view/frontend/templates/js/boltjs.phtml
Labels: enhancement
