Repository BoltApp/bolt-magento2, pull requests merged in 2019-01, with the labels that each got.

#188 Unit test for getShippingMethods() method
  Model/Api/ShippingMethods.php
  Test/Unit/Model/Api/ShippingMethodsTest.php
Labels: test

#202 tax mismatch adjustment
  Helper/Order.php
Labels: enhancement

#205 CI - sudo composer self-update
  Test/scripts/install_magento.sh
Labels: bugfix
