Repository BoltApp/bolt-magento2, pull requests merged in 2019-05, with the labels that each got.

#263 Fix bug - fail to apply coupon if it is only applicable to specific shipping method
  Model/Api/DiscountCodeValidation.php
  Test/Unit/Model/Api/DiscountCodeValidationTest.php
Labels: bugfix

#272 coupon_code undefined / not evaluated if amount exists fix
  Helper/Cart.php
Labels: bugfix

#274 skip inventory validation if the stock is not managed for the item (e…
  Model/Api/CreateOrder.php
Labels: bugfix

#273 fix for validating shipping cost when discount is applied to shipping
  Model/Api/CreateOrder.php
Labels: bugfix

#280 add form_key as a parameter to the requests to back-office controllers
  view/adminhtml/templates/boltpay/js/replacejs.phtml
Labels: bugfix

#279 pre-auth create order shipping validation error code
  Model/Api/CreateOrder.php
Labels: enhancement

#281 add form_key to frontend controller calls - fixes Magento 2.3.x order…
  view/adminhtml/templates/boltpay/js/replacejs.phtml
  view/frontend/templates/js/replacejs.phtml
Labels: bugfix

#283 M 2.3.x back-office redirect url secret / form key issue
  Controller/Adminhtml/Order/Save.php
  Helper/Cart.php
  Helper/Session.php
  Model/Api/CreateOrder.php
Labels: bugfix

#289 report error in email sending routine and continue order processing
  Helper/Order.php
Labels: enhancement

#291 preauth improve SKU based validation
  Model/Api/CreateOrder.php
Labels: bugfix, enhancement

#292 Implement constructor to ensure error code is taken into account (on older versions)
  Exception/BoltException.php
Labels: bugfix

#294 Support Mirasvit Store Credit
  Helper/Cart.php
  Helper/Discount.php
  Plugin/MirasvitCreditQuotePaymentImportDataBeforePlugin.php
  etc/adminhtml/di.xml
  etc/di.xml
Labels: enhancement

#293 Multi-website Support: Fix getApiKey value, webhooks.
  Block/Js.php
  Controller/Adminhtml/Cart/Data.php
  Controller/Adminhtml/Order/Save.php
  Controller/Cart/Data.php
  Controller/Order/Save.php
  Controller/Shipping/Prefetch.php
  Helper/Api.php
  Helper/Cart.php
  Helper/Geolocation.php
  Helper/Hook.php
  Helper/Order.php
  Model/Api/OrderManagement.php
  Model/Api/ShippingMethods.php
  Model/Payment.php
  Test/Unit/Helper/CartTest.php
  Test/Unit/Model/Api/ShippingMethodsTest.php
  view/adminhtml/templates/boltpay/js/replacejs.phtml
  view/frontend/templates/js/replacejs.phtml
Labels: enhancement
