Repository BoltApp/bolt-magento2, pull requests merged in 2020-10, with the labels that each got.

#990 CI - More threads for ci-integration
  Test/scripts/ci-integration.sh
Labels: enhancement

#995 M2P-320 Show validation message and prevent using the pay by link if the token is invalid
  view/adminhtml/templates/boltpay/js/replacejs.phtml
Labels: old

#953 Add script for creating release for magento.com
  create_release.sh
Labels: old

#984 M2P-253 Remove MageWorld RewardPoints from Bolt modal
  Model/Api/UpdateCart.php
  Model/EventsForThirdPartyModules.php
  ThirdPartyModules/MageWorld/RewardPoints.php
Labels: old

#975 M2P-262 - Resolve issue with Aheadworkds_Sarp2
  Model/EventsForThirdPartyModules.php
  Observer/Adminhtml/ActionPredispatch.php
  Test/Unit/Observer/Adminhtml/ActionPredispatchTest.php
  Test/Unit/ThirdPartyModules/Aheadworks/Sarp2Test.php
  ThirdPartyModules/Aheadworks/Sarp2.php
  etc/adminhtml/events.xml
Labels: bugfix
