Repository BoltApp/bolt-magento2, pull requests merged in 2020-05, with the labels that each got.

#665 PPC for product with attributes - unable to complete checkout fix
  view/frontend/templates/button_product_page.phtml
Labels: bugfix

#669 Allow the retry pending hook to authorize the order if its status is pending payment
  Helper/Order.php
  Test/Unit/Helper/OrderTest.php
Labels: old

#679 Add custom url validation
  Helper/Config.php
  Test/Unit/Helper/ConfigTest.php
  etc/adminhtml/system.xml
  view/adminhtml/web/js/validation.js
Labels: old

#681 Unit test: Bolt\Boltpay\Model\FeatureSwitch
  Test/Unit/Model/FeatureSwitchTest.php
Labels: old

#683 Unit test: Bolt\Boltpay\Plugin\ClearQuote
  Test/Unit/Plugin/ClearQuoteTest.php
Labels: old

#684 Add config path for store pickup configurations
  etc/adminhtml/system.xml
Labels: old

#688 Success order redirect does not work for back-office orders
  Controller/Adminhtml/Cart/Data.php
  Controller/Adminhtml/Order/ReceivedUrl.php
  Controller/Order/ReceivedUrl.php
  Test/Unit/Controller/Adminhtml/Order/ReceivedUrlTest.php
  Test/Unit/Controller/Order/ReceivedUrlTest.php
  view/adminhtml/templates/boltpay/js/replacejs.phtml
Labels: old

#690 Unit test: Bolt\Boltpay\Controller\Customer\CreditCard
  Test/Unit/Controller/Customer/CreditCardTest.php
Labels: test

#696 M2P-51 Split Shipping and Tax endpoints
  Api/Data/ShippingDataInterface.php
  Api/Data/ShippingTaxDataInterface.php
  Api/Data/TaxDataInterface.php
  Api/Data/TaxResultInterface.php
  Api/ShippingInterface.php
  Api/TaxInterface.php
  Helper/Cart.php
  Helper/Order.php
  Model/Api/CreateOrder.php
  Model/Api/Data/ShippingData.php
  Model/Api/Data/ShippingOption.php
  Model/Api/Data/TaxData.php
  Model/Api/Data/TaxResult.php
  Model/Api/DiscountCodeValidation.php
  Model/Api/Shipping.php
  Model/Api/ShippingTax.php
  Model/Api/ShippingTaxContext.php
  Model/Api/Tax.php
  Plugin/QuotePlugin.php
  Setup/UpgradeSchema.php
  Test/Unit/Helper/CartTest.php
  Test/Unit/Helper/OrderTest.php
  Test/Unit/Model/Api/Data/ShippingDataTest.php
  Test/Unit/Model/Api/Data/ShippingOptionTest.php
  Test/Unit/Model/Api/Data/ShippingTaxTest.php
  Test/Unit/Model/Api/Data/TaxDataTest.php
  Test/Unit/Model/Api/Data/TaxResultTest.php
  Test/Unit/Model/Api/DiscountCodeValidationTest.php
  Test/Unit/Model/Api/ShippingTaxContextTest.php
  Test/Unit/Model/Api/ShippingTaxTest.php
  Test/Unit/Model/Api/ShippingTest.php
  Test/Unit/Model/Api/TaxTest.php
  Test/Unit/Plugin/QuotePluginTest.php
  Test/Unit/TestHelper.php
  etc/di.xml
  etc/webapi.xml
Labels: enhancement

#699 remove cloning extension attributes
  Helper/Cart.php
  Test/Unit/Helper/CartTest.php
Labels: bugfix
